version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "sqlserver123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  firstapi:
    build: .
    container_name: firstapi
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProjectDB;User Id=sa;Password=sqlserver123;
    depends_on:
      - sqlserver
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
